export const stickScrollBadges = [
	{
		title: "Brand Development & Promotion",
		id: "service-1",
		description: [
			"Brand creation",
			"Brand promotion",
			"Reputation management",
			"Slogans",
			"Taglines",
			"Pitch Decks",
			"Business Naming",
			"Product Naming",
			"Product Branding",
			"Logo Design",
		],
	},
	{
		title: "Copywriting",
		id: "service-2",
		description: [
			"Website Copy",
			"Email Copy",
			"Email Newsletters",
			"Email Design",
			"Authority Copy",
			"E-commerce Store Copy",
			"Product Descriptions",
			"Landing Pages Copy",
			"Ad Copy",
			"Sales Pages Copy",
			"Opt-in Forms",
			"VSL Copy",
			"Subscription Pages Copy",
		],
	},
	{
		title: "Digital Marketingkllljlk",
		id: "service-3",
		description: [
			"Online Marketing Campaign",
			"Sales Funnels",
			"B2B Marketing",
			"B2C Marketing",
			"Social Media Marketing",
			"Google Ads",
			"Facebook Ads",
			"TikTok Ads",
			"Instagram Ads",
		],
	},
	{
		title: "Website Development & SEO",
		id: "service-4",
		description: [
			"Website Development",
			"Website Optimization",
			"SEO",
			"Sales Pages",
			"Landing Pages",
			"E-commerce Stores",
			"Shopify",
			"Framer Motion",
			"Webflow",
			"Feature Development",
		],
	},
	{
		title: "Consulting & Strategy",
		id: "service-5",
		description: [
			"Marketing Strategy",
			"Content Strategy",
			"5 Star Reviews Plans",
			"Product Planning",
			"Launch Day Strategy",
			"SEO Strategy",
			"Social Media Growth",
			"Business Management Consultation",
		],
	},
	{
		title: "Content Creation",
		id: "service-6",
		description: [
			"Instagram Captions",
			"Hashtag Ranking",
			"Trending Content",
			"Social Media Leads",
			"Subscription Based Content",
			"Blog Content",
			"Social Media Content",
			"Video Sales Letter Script",
			"Product Description",
		],
	},
	{
		title: "Analytics & Reporting",
		id: "service-7",
		description: [
			"Performance Tracking",
			"Reporting Insights",
			"A/B Testing",
			"Future Projections",
			"SWOT Analysis",
			"Competition Analytics",
			"Market Research",
			"In-Depth Business Studies",
		],
	},
]
